substitutions:
  name: heatpump
  friendlyName: Ecodan Heatpump

esphome:
  name: ${name}
  friendly_name: ${friendlyName}

esp8266:
  board: esp01_1m
  framework:
    platform_version: 4.2.1

packages:
  ecodan-heatpump: github://r-andelhofs/esphome-ecodan-heatpump/heatpump.yaml@main

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  password: !secret heatpump_ota_password
  platform: esphome

api:
  encryption:
    key: !secret heatpump_encryption_key
